---
version: 2.1

# 実行環境の情報定義
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6.5


commands:
  pip_install:
    description:
      "Installing for needed pip liblary."
    steps:
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
  execute_test:
    description:
      "Execute for test script."
    steps:
      - run: |
          python3 tool/generate_config.py
          . test/test_script.sh

# ジョブ定義
jobs:
  setup:
    executor:
      default
    steps:
      - checkout
      - pip_install
  test:
    executor:
      default
    steps:
      - checkout
      - execute_test
      - attach_workspace:
          at: ~/workspace
workflows:
  setup_deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
