---
version: 2.1

# 実行環境の情報定義
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6.5


commands:
  pip_install:
    steps:
      - run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip -V
        pip install pytest
        pip install pytest-cov

# ジョブ定義
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - pip_install
      - run:
          name: Install Packages
          command: |
            mkdir -p ~/workspace
            echo "Hello World > ~/workspace/bin"
            ls -la ../
      # ビルド/テストコンテナでのファイル共有
      # - persist_to_workspace:
      #     root: ~/workspace
      #     paths:
      #       - bin
  test:
    executor:
      default
    steps:
      - checkout
      - run:
          name: Test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip -V
            pip install pytest
            pip install pytest-cov
      - attach_workspace:
          at: ~/workspace/bin
      - run:
          name: Echo File
          command: |
            cat ~/workspace/bin
workflows:
  setup_deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
